-- -*- lua -*-
--
--
--
--
--
whatis("Name : pycoQC")
whatis("Version : 2.5.2")
help([[PycoQC computes metrics and generates interactive QC plots for Oxford Nanopore technologies sequencing data. PycoQC relies on the sequencing_summary.txt file generated by Albacore and Guppy, but if needed it can also generate a summary file from basecalled fast5 files. The package supports 1D and 1D2 runs generated with Minion, Gridion and Promethion devices, basecalled with Albacore 1.2.1+ or Guppy 2.1.3+. PycoQC is written in pure Python3. Python 2 is not supported. For a quick introduction see tutorial by Tim Kahlke available at https://timkahlke.github.io/LongRead_tutorials/QC_P.html]])

prepend_path("PATH", "/cluster/work/nme/software/apps/pycoQC/2.5.2/bin")
prepend_path("LD_LIBRARY_PATH", "/cluster/work/nme/software/apps/pycoQC/2.5.2")
prepend_path("LIBRARY_PATH", "/cluster/work/nme/software/apps/pycoQC/2.5.2")
prepend_path("PYTHONPATH", "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages:/cluster/work/nme/software/apps/pycoQC/2.5.2")

load("python/3.8.5")
load("hdf5/1.10.1")
